#-------------------------------
# General Site Settings

title: 舞号 | 舞动人生 号召精彩
description: Galada is an easy and simple theme for Jekyll. Dark colors, give it a special exquisite look. A careful approach to design and features make it an ideal solution for a personal blog. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

ionicons:
  woff2:
#-------------------------------
# About Section
author-name:   Natali Anderson
author-avatar: 09.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.



#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
exclude:
  - Gemfile
  - .idea # ignore Minimal Mistakes /.idea
  - Gemfile.lock